# Generated by Django 4.2.4 on 2023-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0003_work_css_file_work_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='project_file',
            field=models.FileField(default='', null=True, upload_to='educational_app/documents'),
        ),
    ]
