# Generated by Django 4.2.4 on 2023-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_app', '0004_alter_work_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='css_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='educational_app/css'),
        ),
    ]
