# Generated by Django 4.2.4 on 2023-08-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='educational_app/images', verbose_name='фото')),
                ('project_file', models.FileField(upload_to='educational_app/docments', verbose_name='файл проекта')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
