# Generated by Django 4.2.4 on 2023-08-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educatioanal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
    ]
